/**
 * @file packages/design-tokens/scripts/build.ts
 * @purpose Token transformation pipeline. Reads src/tokens.json and generates
 * dist/tokens.css (CSS Custom Properties) and dist/tokens.ts (TypeScript object).
 * @interface Build script, run via `pnpm build` in this package.
 * @phase 1
 */

import * as fs from 'fs';
import * as path from 'path';
import tokens from '../src/tokens.json';

// --- Type Definitions ---

type TokenValue = string | number;

interface TokenNode {
  value?: TokenValue;
  type?: string;
  [key: string]: TokenValue | TokenNode | undefined;
}

type TokenData = Record<string, TokenNode>;

// --- Paths ---
const SRC_DIR = path.resolve(__dirname, '../src');
const DIST_DIR = path.resolve(__dirname, '../dist');
const CSS_OUTPUT_PATH = path.resolve(DIST_DIR, 'tokens.css');
const TS_OUTPUT_PATH = path.resolve(DIST_DIR, 'tokens.ts');

// --- Helper Functions ---

/**
 * Flattens the nested token JSON object.
 * @param obj - The token object to flatten.
 * @param prefix - The prefix for the current level.
 * @returns A flat map of token paths to their values.
 */
function flattenTokens(obj: TokenData | TokenNode, prefix = ''): Map<string, TokenValue> {
  const result = new Map<string, TokenValue>();

  for (const key in obj) {
    if (key === 'value') continue; // Skip 'value' key itself

    const node = obj[key as keyof typeof obj] as TokenNode;
    const newPrefix = prefix ? `${prefix}-${key}` : key;

    if (node.value !== undefined) {
      result.set(newPrefix, node.value);
    } else if (typeof node === 'object' && node !== null && !Array.isArray(node)) {
      const nested = flattenTokens(node, newPrefix);
      nested.forEach((value, key) => result.set(key, value));
    }
  }
  return result;
}

/**
 * Generates the content for tokens.css
 * @param flatTokens - A map of flattened token keys and values.
 * @returns A string containing the CSS file content.
 */
function createCssContent(flatTokens: Map<string, TokenValue>): string {
  let css = `:root {\n`;
  css += `  /* =====================================================\n`;
  css += `     LimeAura Design Tokens (Generated)\n`;
  css += `     Do not edit this file directly.\n`;
  css += `     ===================================================== */\n\n`;

  flatTokens.forEach((value, key) => {
    css += `  --${key}: ${value};\n`;
  });

  css += `}\n`;
  return css;
}

/**
 * Generates the content for tokens.ts
 * @param flatTokens - A map of flattened token keys and values.
 * @returns A string containing the TypeScript file content.
 */
function createTsContent(flatTokens: Map<string, TokenValue>): string {
  const tokenObject: Record<string, any> = {};

  flatTokens.forEach((value, key) => {
    const keys = key.split('-');
    let current = tokenObject;
    keys.forEach((k, index) => {
      if (index === keys.length - 1) {
        // Last key, assign the CSS variable reference
        current[k] = `var(--${key})`;
      } else {
        // Create nested object if it doesn't exist
        current[k] = current[k] || {};
        current = current[k];
      }
    });
  });

  let ts = `/* =====================================================\n`;
  ts += `   LimeAura Design Tokens (Generated)\n`;
  ts += `   Do not edit this file directly.\n`;
  ts += `   ===================================================== */\n\n`;
  ts += `export const tokens = ${JSON.stringify(tokenObject, null, 2)} as const;\n\n`;
  ts += `export type Tokens = typeof tokens;\n`;
  return ts;
}

// --- Main Build Function ---

function build() {
  console.log('Building design tokens...');

  try {
    // 1. Ensure dist directory exists
    if (!fs.existsSync(DIST_DIR)) {
      fs.mkdirSync(DIST_DIR, { recursive: true });
    }

    // 2. Flatten tokens
    const flatTokens = flattenTokens(tokens as TokenData);
    console.log(`Found ${flatTokens.size} tokens.`);

    // 3. Generate CSS content
    const cssContent = createCssContent(flatTokens);
    fs.writeFileSync(CSS_OUTPUT_PATH, cssContent, 'utf-8');
    console.log(`Successfully wrote CSS to ${CSS_OUTPUT_PATH}`);

    // 4. Generate TS content
    const tsContent = createTsContent(flatTokens);
    fs.writeFileSync(TS_OUTPUT_PATH, tsContent, 'utf-8');
    console.log(`Successfully wrote TS to ${TS_OUTPUT_PATH}`);

    console.log('Design tokens build complete! ✨');
  } catch (error) {
    console.error('Error building design tokens:', error);
    process.exit(1);
  }
}

// Run the build
build();
